name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: windows-latest  # ⚡直接在Windows环境构建，无需Wine！

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller pynput

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --name KeyboardController main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-EXE
          path: dist/KeyboardController.exe

      - name: Upload Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.upload-release-asset-upload-url.outputs.upload_url }}
          asset_path: dist/KeyboardController.exe
          asset_name: KeyboardController.exe
          asset_content_type: application/octet-stream
          asset_label: Windows-EXE